app:
  kafka:
    enabled: true
    host: ${kafka_bootstrap_servers:192.168.182.145:9092}
    topic: test_topic
    max-poll-record: 1000
    consumer-group-id: user-consumer-test

server:
  port: 8080
